apiVersion: apps/v1
kind: Deployment
metadata: 
  name: javawebrs
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: javawebapp
  strategy:
    type: Recreate	
  template: 
    metadata:
      name: javawebapppod
      labels: 
        app: javawebapp
    spec: 
      containers:
      - name: javawebappcontainer
        image: venuprathap/java-web-app:v1
        ports:
        - name: javawebapp
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: javawebelb
spec:
  selector:
    app: javawebapp
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
