---    
apiVersion: v1
kind: PersistentVolumeClaim        
metadata:                          
  name: pvc-hostpath
  labels:
    app: mongo
spec:                              
  storageClassName: standard       
  accessModes:
    - ReadWriteOnce                
  resources:
    requests:
      storage: 250Mi

