apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: springbootrs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template: 
    metadata:
      name: springbootpod
      labels: 
        app: springboot
    spec: 
      containers:
      - name: springbootcontainer
        image: venuprathap/spring-boot-mongo:2
        ports:
        - name: springboot
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springbootnp
spec:
  selector:
    app: springboot
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
